version: '2.0'
services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile.web
    environment:
      - BOT_TOKEN=$BOT_TOKEN
      - EMAIL_DESTINATION=$EMAIL_DESTINATION
      - EMAIL_SOURCE=$EMAIL_SOURCE
      - SENDGRID_API_KEY=$SENDGRID_API_KEY
    ports:
    - "3000:3000"
